server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activiti
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: maxinyu

  # activiti default configuration
  #activiti:
    #database-schema-update: true
    #check-process-definitions: true
    #process-definition-location-prefix: classpath:/processes/
#    process-definition-location-suffixes:
#      - **.bpmn
#      - **.bpmn20.xml
    #history-level: full

